* freshmodl
** Requirements
- https://cookiecutter.readthedocs.io
- Most of the cookiecutters probably make use of nix, so having working knowledge of nix or willingness to lean into the intricacies of nix is assumed.
- insanity (we need more insanity)
** How I create and maintain these?
#+begin_quote
Whenever I find something worth adding to the original template while working on other projects I just update the template. Too bad it'll not update the downstream projects but I am making that tradeoff. I checked [[https://github.com/cruft/cruft][cruft]], but I think once a project takes off from a cookie-cutter/boilerplate, there's no looking back. Just keep making forward progress. There are some cases where consistency is important but the way I develop things that's not the case. So we use plain old cookiecutter.
#+end_quote
- Replacement
  - Once I make sure the project is working with placeholder(usually "dummy")
  - Then I just ~rg -l "placeholder" | xargs sd "placeholder" "{{cookiecutter.var_name}}"~
- Testing:
  - ~cookiecutter . --output-dir /tmp --replay --overwrite-if-exists~
* Others
- See the [[https://github.com/orgs/community/discussions/5336
][sorry state of github templates]]
