justfile_project_slug := "TODO:UPDATE_THIS_MANUALLY" # should match cookiecutter.json:project_slug variable

default:
	@just --list

test-run:
	cookiecutter . --output-dir . --overwrite-if-exists

_check:
	echo "TODO: If your project has test/formatting/linting checks, run them here"

# The replace recipe needs to be customized for your specific cookiecutter.
# This is a placeholder implementation.
replace: _check
	#!/bin/bash
	set -eu

	cd {{justfile_project_slug}}
	# EXAMPLE: Replace placeholder in files
	# rg -l "dummy_project_name" | xargs -r sd "dummy_project_name" "{{ '{{' }}cookiecutter.project_slug}}"

	echo "TODO: Implement your replacement logic here."

diff:
	git clean -f -X -d {{justfile_project_slug}}/
	git clean -f -X -d "./{{ '{{' }}cookiecutter.project_slug}}"
	git diff --no-index --find-renames "./{{ '{{' }}cookiecutter.project_slug}}" {{justfile_project_slug}}/

# ONLY run this when you're finally ready to migrate
# the new template after manually checking the diff
move:
	rm -rf "{{ '{{' }}cookiecutter.project_slug}}"
	mv "{{justfile_project_slug}}" "{{ '{{' }}cookiecutter.project_slug}}"
