* AI-RULES
Cookie cutter to add AI rules and files for various AI agents.

Currently tested with:
- cline
- windsurf

If you're looking for how to do AI assisted coding(this repo follows all the ideas mentioned here), check:

** Usage
This project-agnostic cookiecutter can be used in a new or existing repository.
*** Setup
First ~cd~ inside the directory where you store project level docs. Usually ~/docs~. And run run the following:
#+begin_src shell
# NOTE: docs_path should be relative to repository root
cruft create \
--overwrite-if-exists \
https://github.com/alwaysbecooking/freshmold.git \
--directory="misc/ai-rules"
#+end_src
- This will create a ~.cruft.json~ file in your newly created directory. You should check this in version control.
- After the first fetch (~cruft create~), you should manually skim through all the rules and delete the ones that you do not need.
*** Management/Update
- Use ~cruft check~, ~cruft diff~ and ~cruft update~. You might need to use ~GIT_PAGER=cat cruft update~ to get the diff view correct. While doing so you have the option to skip new rules, from the diff etc.
- Try avoiding editing the rules that you've fetched directly, instead edit them upstream and run ~cruft update~.
  - If you by any chance edit the same line in your working repository as the updated rules in upsteam happens, ~cruf~ will not raise an conflict instead it'll have the conflict showing up directly in the file. Which you have to fix manually. This shows up in git diff so not the biggest problem.
*** Using these rules with your AI editor
- Use the rules as contexts (~@mention~) when trying to enforce certain rule. Otherwise The management of the rules is specific to each AI agent, eg. Cursor follows different convention, windsurf follows a different convention, Amp is different etc. So you can adjust things accordingly. For common rules, I put things under ~.clinerules/~ directory.
- If you're using a monorepo, you'd be switching back and forth between the rules

Following are ~Justfile/Makefile~ entries based on whichever agent you're using: (Copy manually as per need)
#+begin_src makefile
cline-meta-ai-rules:
	mkdir -p .clinerules
	rg -F "^.clinerules/$" .gitignore > /dev/null || echo ".clinerules/" >> .gitignore
	cp ./docs/for_ai/rules/meta_* ./.clinerules/
#+end_src
**** AI Ignore files
AI agents would usually have a file which you can use to instruct about files it should avoid reading. Put the following in it. Eg. for cline, that ~.clineignore~
#+begin_src
# Dependencies
node_modules/
**/node_modules/
.pnp
.pnp.js

# Build outputs
/build/
/dist/
/out/

# Testing
/coverage/

# Environment variables
.env
.envrc
.env.local
.env.development.local
.env.test.local
.env.production.local

# Large data files
*.csv
*.xlsx
#+end_src
