image_repo := "some_repository"
image_name := "{{cookiecutter.project_slug}}"
image_id := "latest"
platform := if `nix eval --impure --raw --expr 'builtins.currentSystem'` == "x86_64-linux" { "amd64" } else { "arm64" }
image_tag := image_id + "_" + platform
image_file := image_name + "_" + image_tag

default:
	@just --list

test:
	python -m pytest -v -s "$@"

# Run the linter to check for issues
_check-lint:
    @echo "Linting with Ruff..."
    @ruff check .

# Run the static type checker
_check-type:
    @echo "Type checking with Mypy..."
    @mypy .

# Run the security scanner
_check-security:
    @echo "Scanning for security issues with Bandit..."
    @bandit -r src

# run code checks
check: _check-lint _check-type _check-security

# Apply formatting in-place
_fix-format:
    @echo "Formatting with Black..."
    @black .

# Let the linter try to automatically fix issues
_fix-lint:
    @echo "Fixing lint issues with Ruff..."
    @ruff check --fix .

# Let the linter try to automatically fix issues (forced)
_fix-lint-force:
    @echo "Fixing lint issues with Ruff..."
    @ruff check --fix --unsafe-fixes .

# fix everything that can be fixed automatically
fix: _fix-lint _fix-format
fix-force: _fix-lint-force _fix-format

# run the worker
{{cookiecutter.project_slug}}-server:
  uv run server

docker-build:
	IMAGE_NAME={% raw %}{{image_repo}}{% endraw %}/{% raw %}{{image_name}}{% endraw %} \
	IMAGE_TAG={% raw %}{{image_tag}}{% endraw %} \
	nix build -o ./results/{% raw %}{{image_file}}{% endraw %} \
	--impure --show-trace .#{{cookiecutter.project_slug}}_docker

docker-load:
	docker load < ./results/{% raw %}{{image_file}}{% endraw %}

docker-run:
	docker run --rm \
	-it {% raw %}{{image_repo}}{% endraw %}/{% raw %}{{image_name}}{% endraw %}:{% raw %}{{image_tag}}{% endraw %}

docker-push:
	docker push {% raw %}{{ image_repo }}{% endraw %}/{% raw %}{{image_name}}{% endraw %}:{% raw %}{{image_tag}}{% endraw %}

docker-manifest-push:
	docker pull "{% raw %}{{ image_repo }}{% endraw %}/{% raw %}{{image_name}}{% endraw %}:{% raw %}{{image_id}}{% endraw %}_amd64"
	docker pull "{% raw %}{{ image_repo }}{% endraw %}/{% raw %}{{image_name}}{% endraw %}:{% raw %}{{image_id}}{% endraw %}_arm64"

	docker manifest create "{% raw %}{{ image_repo }}{% endraw %}/{% raw %}{{ image_name }}{% endraw %}:{% raw %}{{ image_id }}{% endraw %}" \
	--amend "{% raw %}{{ image_repo }}{% endraw %}/{% raw %}{{ image_name }}{% endraw %}:{% raw %}{{ image_id }}{% endraw %}_amd64" \
	--amend "{% raw %}{{ image_repo }}{% endraw %}/{% raw %}{{ image_name }}{% endraw %}:{% raw %}{{ image_id }}{% endraw %}_arm64"

	docker manifest push "{% raw %}{{ image_repo }}{% endraw %}/{% raw %}{{ image_name }}{% endraw %}:{% raw %}{{ image_id }}{% endraw %}"
