justfile_project_slug := "dummy_project_name" # should match cookiecutter.json:project_slug variable

default:
	@just --list

test-run:
	cookiecutter . --output-dir . --overwrite-if-exists

_check:
	cd {{justfile_project_slug}} && NIXPKGS_ALLOW_UNFREE=1 nix develop --impure --command just test
	cd {{justfile_project_slug}} && NIXPKGS_ALLOW_UNFREE=1 nix develop --impure --command just check
	cd {{justfile_project_slug}} && NIXPKGS_ALLOW_UNFREE=1 nix develop --impure --command just fix

# The replace recipe needs to be customized for your specific cookiecutter.
# This is a placeholder implementation.
replace: _check
	#!/bin/bash
	set -eu

	cd {{justfile_project_slug}}
	rg -l "{{justfile_project_slug}}" | xargs -r sd "{{justfile_project_slug}}" "{{ '{{' }}cookiecutter.project_slug}}"
	rg -l "dummy" | xargs -r sd "dummy" "{{ '{{' }}cookiecutter.python_package_name}}"
	mv src/dummy "src/{{ '{{' }}cookiecutter.python_package_name}}"

	echo "might have to fix few replacements manually, eg. Justfile(we do have a AI rule about that)"

diff:
	git clean -f -X -d {{justfile_project_slug}}/
	git clean -f -X -d "./{{cookiecutter.project_slug}}"
	git diff --no-index --find-renames "./{{cookiecutter.project_slug}}" {{justfile_project_slug}}/

# ONLY run this when you're finally ready to migrate
# the new template after manually checking the diff
move:
	rm -rf "{{cookiecutter.project_slug}}"
	mv "{{justfile_project_slug}}" "{{cookiecutter.project_slug}}"
